server:
  port: 8001
  context-path:
# 数据源配置
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/tobacco
    driver-class-name: com.mysql.jdbc.Driver
#配置mybatis参数
#mybatis:
#  config-location: classpath:mybaits/mybatis-config.xml
#  mapper-locations: classpath:mybatis/mapper/*.xml
logging:
  level: debug