server:
  port: 8001
  context-path:
# 数据源配置
spring:
  datasource:
    username: root
    password: Yc171013@
    url: jdbc:mysql://139.224.192.190:3306/tobacco?characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
      enabled: true
      resolve-lazily: false

#配置mybatis参数
#mybatis:
#  config-location: classpath:mybaits/mybatis-config.xml
#  mapper-locations: classpath:mybatis/mapper/*.xml
logging:
  level: debug
logging.level.com.xr.base.mapper: debug

mybatis:
  typeAliasesPackage: com.xr.base.entity
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true